tag:
  - planing_task
task: countdown
dataset_path: json
dataset_kwargs:
  data_files: eval/tasks/countdown/countdown.jsonl
test_split: train
output_type: generate_until
process_docs: !function utils.process_docs
doc_to_text: !function utils.doc_to_text
doc_to_target: !function utils.doc_to_target
process_results: !function utils.process_results
generation_kwargs:
  until:
    - "Question:"
  do_sample: false
  temperature: 0
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
metadata:
  version: 3.0
num_fewshot: 3
fewshot_delimiter: "\n\n"
fewshot_config:
  sampler: first_n
  samples: !function utils.list_fewshot_samples